apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: backend
          image: silverspark/zuriapp-backend:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: API_SECRET_KEY
          readinessProbe:
            httpGet:
              path: /api/store
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
